[target.x86_64-unknown-linux-musl]
rustflags = "-Ctarget-feature=-crt-static"

[target.aarch64-unknown-linux-musl]
rustflags = "-Ctarget-feature=-crt-static"

[registries.artifactory]
index = "sparse+https://zettascale.jfrog.io/artifactory/api/cargo/zetta-qnx/index/"
credential-provider = ["cargo:token"]
