#
# Copyright (c) 2023 ZettaScale Technology
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   ZettaScale Zenoh Team, <zenoh@zettascale.tech>
#
name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  schedule:
    - cron: "0 6 * * 1-5"

env:
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
  CARGO_PROFILE_DEV_DEBUG: false

jobs:
  tests:
    name: Tests
    needs: checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [ "ubuntu:22.04" ]
    container: ${{ matrix.image }}
    steps:
      - name: Update and install packages
        run: apt-get update && apt-get install -y curl git build-essential pkg-config libssl-dev

      - name: Install Rust toolchain
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Clone this repository
        uses: actions/checkout@v4

      - name: Install nextest
        run: cargo +stable install --locked cargo-nextest
        env:
          CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

      - name: Run tests
        run: cargo nextest run --release --features=${{ inputs.features }} --verbose
        env:
          CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
